-- 0008_branch_kcn.sql — เปิดสาขา KCN (Kanchanapisek)
-- Opening stock = 0 ทุกไอเทม (ไม่มี stock_daily/sales_daily/cup_reconcile row ก่อนหน้า → carry-forward
-- logic ใน getStock คืน carryPack=0/carryG=0 โดยอัตโนมัติ ไม่ต้อง insert อะไรเพิ่มสำหรับตารางเหล่านั้น)

-- 1) สาขาใหม่
insert into branches (id, name) values
  ('KCN', 'Kanchanapisek')
on conflict (id) do nothing;

-- 2) par_levels: เติมแถว KCN ให้ทุก item (ตัวเลข par จริงจากแพร — รายการที่ไม่ระบุ = null = "ยังไม่กำหนด/ไม่ stock")
insert into par_levels (item_id, branch_id, level) values
  ('it-001', 'KCN', 3),
  ('it-002', 'KCN', null),
  ('it-003', 'KCN', null),
  ('it-004', 'KCN', null),
  ('it-005', 'KCN', null),
  ('it-006', 'KCN', null),
  ('it-007', 'KCN', null),
  ('it-008', 'KCN', null),
  ('it-009', 'KCN', 3),
  ('it-010', 'KCN', 7),
  ('it-011', 'KCN', 2),
  ('it-012', 'KCN', null),
  ('it-013', 'KCN', null),
  ('it-014', 'KCN', null),
  ('it-015', 'KCN', null),
  ('it-016', 'KCN', null),
  ('it-017', 'KCN', null),
  ('it-018', 'KCN', null),
  ('it-019', 'KCN', null),
  ('it-020', 'KCN', 5),
  ('it-021', 'KCN', 5),
  ('it-022', 'KCN', 5),
  ('it-023', 'KCN', 5),
  ('it-024', 'KCN', 5),
  ('it-025', 'KCN', 5),
  ('it-026', 'KCN', null),
  ('it-027', 'KCN', null),
  ('it-028', 'KCN', null),
  ('it-029', 'KCN', null),
  ('it-030', 'KCN', null),
  ('it-031', 'KCN', null),
  ('it-032', 'KCN', null),
  ('it-033', 'KCN', null),
  ('it-034', 'KCN', null),
  ('it-035', 'KCN', null),
  ('it-036', 'KCN', null),
  ('it-037', 'KCN', null),
  ('it-038', 'KCN', null),
  ('it-039', 'KCN', null),
  ('it-040', 'KCN', null),
  ('it-041', 'KCN', null),
  ('it-042', 'KCN', null),
  ('it-043', 'KCN', null),
  ('it-044', 'KCN', null),
  ('it-045', 'KCN', null),
  ('it-046', 'KCN', null),
  ('it-047', 'KCN', null),
  ('it-048', 'KCN', null),
  ('it-049', 'KCN', null),
  ('it-050', 'KCN', null),
  ('it-051', 'KCN', null),
  ('it-052', 'KCN', null),
  ('it-053', 'KCN', null),
  ('it-054', 'KCN', null),
  ('it-055', 'KCN', null),
  ('it-056', 'KCN', null),
  ('it-057', 'KCN', null),
  ('it-058', 'KCN', null),
  ('it-059', 'KCN', null),
  ('it-060', 'KCN', null),
  ('it-061', 'KCN', null),
  ('it-062', 'KCN', null),
  ('it-063', 'KCN', null),
  ('it-064', 'KCN', null),
  ('it-065', 'KCN', null),
  ('it-066', 'KCN', null),
  ('it-067', 'KCN', null),
  ('it-068', 'KCN', null),
  ('it-069', 'KCN', null),
  ('it-070', 'KCN', null),
  ('it-071', 'KCN', null),
  ('it-072', 'KCN', null),
  ('it-073', 'KCN', null),
  ('it-074', 'KCN', null),
  ('it-075', 'KCN', null),
  ('it-076', 'KCN', null),
  ('it-077', 'KCN', null),
  ('it-078', 'KCN', null),
  ('it-079', 'KCN', null),
  ('it-080', 'KCN', null),
  ('it-081', 'KCN', null),
  ('it-082', 'KCN', null),
  ('it-083', 'KCN', null),
  ('it-084', 'KCN', null),
  ('it-085', 'KCN', null),
  ('it-086', 'KCN', null),
  ('it-087', 'KCN', null),
  ('it-088', 'KCN', null),
  ('it-089', 'KCN', null),
  ('it-090', 'KCN', null),
  ('it-091', 'KCN', null),
  ('it-092', 'KCN', null),
  ('it-093', 'KCN', null),
  ('it-094', 'KCN', null),
  ('it-095', 'KCN', null),
  ('it-096', 'KCN', null),
  ('it-097', 'KCN', null),
  ('it-098', 'KCN', null),
  ('it-099', 'KCN', null),
  ('it-100', 'KCN', null),
  ('it-101', 'KCN', null),
  ('it-102', 'KCN', null),
  ('it-103', 'KCN', null),
  ('it-104', 'KCN', null),
  ('it-105', 'KCN', null),
  ('it-106', 'KCN', null),
  ('it-107', 'KCN', null),
  ('it-108', 'KCN', null),
  ('it-109', 'KCN', null),
  ('it-110', 'KCN', null),
  ('it-111', 'KCN', null),
  ('it-112', 'KCN', null)
on conflict (item_id, branch_id) do nothing;

notify pgrst, 'reload schema';
