-- เพิ่ม check_frequency + show_remainder ให้ items (ปรับปรุงหน้าสต็อก/เติมของ 2026-07-18)
-- check_frequency: 'daily' ทุกวัน | 'monThu' เฉพาะจันทร์+พฤหัส (ของหมุนช้า ลดภาระกรอกซ้ำ — ยืนยันกับแพรแล้ว)
-- show_remainder: หน้าเติมของโชว์ "แพ็คเต็ม + เศษกรัมที่เปิดแล้ว" แทนแค่จำนวนแพ็ค (41 รายการที่แพรระบุ)

alter table items add column if not exists check_frequency text not null default 'daily';
alter table items add column if not exists show_remainder boolean not null default false;

update items as i set
  check_frequency = v.freq,
  show_remainder = v.show_rem
from (values
('it-001','daily',true),
('it-002','daily',true),
('it-003','daily',true),
('it-004','daily',true),
('it-005','daily',true),
('it-006','daily',true),
('it-007','daily',true),
('it-008','daily',true),
('it-009','daily',true),
('it-010','daily',false),
('it-011','daily',false),
('it-012','daily',false),
('it-013','daily',false),
('it-014','daily',true),
('it-015','daily',true),
('it-016','daily',false),
('it-017','daily',false),
('it-018','monThu',false),
('it-019','monThu',false),
('it-020','daily',false),
('it-021','daily',false),
('it-022','daily',false),
('it-023','daily',false),
('it-024','daily',false),
('it-025','daily',false),
('it-026','daily',false),
('it-027','daily',false),
('it-028','daily',false),
('it-029','monThu',true),
('it-030','monThu',true),
('it-031','monThu',true),
('it-032','monThu',true),
('it-033','monThu',true),
('it-034','monThu',true),
('it-035','monThu',true),
('it-036','monThu',true),
('it-037','monThu',true),
('it-038','monThu',true),
('it-039','monThu',true),
('it-040','monThu',true),
('it-041','monThu',true),
('it-042','monThu',true),
('it-043','daily',false),
('it-044','daily',false),
('it-045','daily',false),
('it-046','daily',false),
('it-047','daily',false),
('it-048','daily',true),
('it-049','daily',false),
('it-050','monThu',true),
('it-051','monThu',true),
('it-052','monThu',true),
('it-053','daily',false),
('it-054','daily',false),
('it-055','daily',false),
('it-056','daily',false),
('it-057','monThu',false),
('it-058','monThu',false),
('it-059','monThu',false),
('it-060','monThu',false),
('it-061','monThu',false),
('it-062','monThu',false),
('it-063','monThu',false),
('it-064','monThu',false),
('it-065','monThu',false),
('it-066','monThu',false),
('it-067','monThu',false),
('it-068','monThu',false),
('it-069','monThu',false),
('it-070','monThu',false),
('it-071','monThu',false),
('it-072','monThu',false),
('it-073','monThu',false),
('it-074','monThu',false),
('it-075','monThu',false),
('it-076','monThu',false),
('it-077','monThu',false),
('it-078','monThu',false),
('it-079','monThu',false),
('it-080','monThu',false),
('it-081','monThu',false),
('it-082','monThu',false),
('it-083','monThu',false),
('it-084','monThu',false),
('it-085','monThu',false),
('it-086','monThu',false),
('it-087','monThu',false),
('it-088','monThu',false),
('it-089','monThu',false),
('it-090','monThu',false),
('it-091','monThu',false),
('it-092','monThu',false),
('it-093','monThu',false),
('it-094','monThu',false),
('it-095','monThu',false),
('it-096','daily',false),
('it-097','daily',false),
('it-098','daily',false),
('it-099','daily',false),
('it-100','monThu',true),
('it-101','monThu',true),
('it-102','monThu',true),
('it-103','monThu',true),
('it-104','monThu',true),
('it-105','monThu',false),
('it-106','monThu',true),
('it-107','monThu',true),
('it-108','monThu',true),
('it-109','monThu',true),
('it-110','monThu',true),
('it-111','monThu',true),
('it-112','monThu',true),
('it-113','daily',false)
) as v(id, freq, show_rem)
where i.id = v.id;
